### ISSUE TITLE
Check for commonly used modules like xdebug

### ISSUE THREAD

**Issue by DeepDreamer89** [sektioneins/pcc#11]
The PHP.ini could be checked against loaded modules like zend_extension=xdebug.so. Xdebug for example is commonly used but should not be available in production environment. Is such a check wished?

**Comment by bef** [comment]
Are there any other extensions worth checking for in a security context?

**Comment by jvoisin** [comment]
I sent a pull-request for [vld]( https://github.com/sektioneins/pcc/pull/25/files ), and well as [runkit]( https://github.com/sektioneins/pcc/pull/24/files )

**Comment by bef** [comment]
These pull-requests have been merged. Thanks.
