### ISSUE TITLE
Any new updates?

### ISSUE THREAD

**Issue by quantuumsnot** [sektioneins/pcc#37]
Just wondering, for example under PHP 8.x there's a deprecation warning at line 1098 about `return "\033[${color}m$result\033[0m";` (fixable with `{$color}`)

**Comment by bef** [comment]
Thank you for asking. I'll be on this soon, but feel free to to contribute a patch or merge request in the meantime.

**Comment by quantuumsnot** [comment]
Ok, just to know I found some strange `string` to `int` conversion at line 223 in `ini_atol()` when `declare(strict_types = 1)` is used:

```
Fatal error: Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, int given in D:\repos\sics\phpconfigcheck.php:223
Stack trace:
#0 D:\repos\sics\phpconfigcheck.php(223): strtolower(268435456)
#1 D:\repos\sics\phpconfigcheck.php(410): ini_atol(268435456)
#2 D:\repos\sics\phpconfigcheck.php(880): test_all_ini_entries()
#3 {main}
  thrown in D:\repos\sics\phpconfigcheck.php on line 223
```
Probably at line 410 passed `$val` values are not properly formatted?

**Comment by bef** [comment]
Thanks for pointing that out.
