### ISSUE TITLE
False positive: suhosin.log.file.name in document root (when none present)

### ISSUE THREAD

**Issue by LewisR** [sektioneins/pcc#9]
Bravo! Nicely done, and very handy auditing tool.

pcc tells me:

```
suhosin.log.file.name in document root
Checks if suhosin.log.file.name path is in the current document root
```

I have not installed the module or the patch.

OS: OS/2
Apache: 2.2.29
PHP: 5.4.36 (as module)

**Comment by bef** [comment]
OS/2? seriously? ok.
Unfortunately I cannot reproduce the problem.

Please provide the output of

    var_dump(ini_get("suhosin.log.file.name"));

**Comment by LewisR** [comment]
I don't know why OS/2 wouldn't be serious. It is still deeply entrenched in a number of Fortune 500 companies in the US and in large companies around the world. It's just not as visible as some other OSes.

Meanwhile, with the suhosin module not loaded, and no suhosin configuration entries in php.ini, the output of the var_dump is:

```
bool(false)
```
which is what I would expect. With the suhosin module loaded, this returns:

```
string(0) ""
```
also what I would expect (because we know what that option is).

The code around line 996 appears to be at fault:

```
/* ===== known, but extra check below. ===== */
		case 'error_log':
		case 'include_path':
		case 'mail.log':
		case 'suhosin.log.file.name':
		case 'upload_tmp_dir':
			// silently ignore this option
			$ignore = 1;
			break;
```
All other options are known to the base php configuration except suhosin.log.file.name. Thus, without the suhosin patch or module, this will return false, triggering the notice.

I haven't checked this against a Linux-based Apache install or on a newer PHP (yes, we have PHP 5.6 for OS/2).
